$(info "lib-gd32/Makefile.GD32")
$(info $$FAMILY [${FAMILY}])
$(info $$MAKE_FLAGS [${MAKE_FLAGS}])

DEFINES=NDEBUG

EXTRA_SRCDIR=src/f

ifneq ($(MAKE_FLAGS),)
  	EXTRA_SRCDIR+=gd32f30x/CMSIS/GD/GD32F30x/Source
  
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_adc.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_bkp.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_dma.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_exti.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_fmc.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_fwdgt.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_gpio.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_i2c.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_pmu.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_rcu.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_rtc.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_spi.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_usart.c
  	EXTRA_C_SOURCE_FILES+=gd32f30x/GD32F30x_standard_peripheral/Source/gd32f30x_timer.c
else
	EXTRA_SRCDIR+=src/uart0 
	EXTRA_SRCDIR+=src/softuart0
endif

include Rules.mk
include ../firmware-template-gd32/lib/Rules.mk